### PR TITLE
Bugfix 417: Sometimes amount text boxes in the split editor fail getting the focus

### LINKED ISSUE #417: Sometimes amount text boxes in the split editor fail getting the focus
Sometimes, when trying to switch the focus from a split memo text box to a amount text box, the focus remains in the memo one. However, the system keyboard is closed and the calculator one is opened. If something is typed with the calculator, the application crashes:
```
E/InputEventReceiver: Exception dispatching input event.
E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI: java.lang.ClassCastException: android.support.v7.widget.AppCompatEditText cannot be cast to org.gnucash.android.ui.util.widget.CalculatorEditText
E/MessageQueue-JNI:     at org.gnucash.android.ui.util.widget.CalculatorKeyboard$1.onKey(CalculatorKeyboard.java:78)
E/MessageQueue-JNI:     at android.inputmethodservice.KeyboardView.detectAndSendKey(KeyboardView.java:827)
E/MessageQueue-JNI:     at android.inputmethodservice.KeyboardView.onModifiedTouchEvent(KeyboardView.java:1349)
E/MessageQueue-JNI:     at android.inputmethodservice.KeyboardView.onTouchEvent(KeyboardView.java:1212)
E/MessageQueue-JNI:     at android.view.View.dispatchTouchEvent(View.java:8486)
E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2541)
E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2234)
E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2541)
E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2234)
E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2541)
E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2234)
E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2541)
E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2234)
E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2541)
E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2234)
E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2541)
E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2234)
E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2541)
E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2234)
E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2541)
E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2234)
E/MessageQueue-JNI:     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2365)
E/MessageQueue-JNI:     at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1726)
E/MessageQueue-JNI:     at android.app.Activity.dispatchTouchEvent(Activity.java:2772)
E/MessageQueue-JNI:     at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
E/MessageQueue-JNI:     at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
E/MessageQueue-JNI:     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2326)
E/MessageQueue-JNI:     at android.view.View.dispatchPointerEvent(View.java:8687)
E/MessageQueue-JNI:     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4485)
E/MessageQueue-JNI:     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4343)
E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3884)
E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3937)
E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3903)
E/MessageQueue-JNI:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4013)
E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3911)
E/MessageQueue-JNI:     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4070)
E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3884)
E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3937)
E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3903)
E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3911)
E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3884)
E/MessageQueue-JNI:     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6300)
E/MessageQueue-JNI:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6256)
E/MessageQueue-JNI:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6209)
E/MessageQueue-JNI:     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6462)
E/MessageQueue-JNI:     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
E/MessageQueue-JNI:     at android.os.MessageQueue.nativePollOnce(Native Method)
E/MessageQueue-JNI:     at android.os.MessageQueue.next(MessageQueue.java:143)
E/MessageQueue-JNI:     at android.os.Looper.loop(Looper.java:146)
E/MessageQueue-JNI:     at android.app.ActivityThread.main(ActivityThread.java:5532)
E/MessageQueue-JNI:     at java.lang.reflect.Method.invoke(Native Method)
E/MessageQueue-JNI: 	at java.lang.reflect.Method.in
```

To reproduce, just keep tapping between the amount and memo text boxes until it happens.

### PR DESCRIPTION
**Pull request by rivaldi8**
Fixes #417.

All about this issue has been very tricky, so please, check nothing new gets broken with the fix.

### CODE REVIEW

File: app/src/main/java/org/gnucash/android/ui/util/widget/CalculatorEditText.java [hunk 1]
```diff
@@ -192,57 +186,7 @@ public CalculatorKeyboard getCalculatorKeyboard(){
     }
 
     /**
-     * Returns the view Id of the keyboard view
```
Comment (codinguser) [inline app/src/main/java/org/gnucash/android/ui/util/widget/CalculatorEditText.java]: These methods are probably marked in the IDE as unused, but they are there because the documentation recommends having them when creating custom views http://goo.gl/6Sg4f . So I would prefer to leave them in. 

Also the keyboardKeysLayout can be set in XML and thereby manipulated programmatically (even if we don't do so at the moment).

Comment (rivaldi8) [inline app/src/main/java/org/gnucash/android/ui/util/widget/CalculatorEditText.java]: Sorry, I'll be more careful next time.
